version: '3.2'

services:
  app:
    restart: always
    build: .
    container_name: app-ticketfy
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - postgres
      - migration
    env_file:
      - .env

  postgres:
    image: postgres
    container_name: database-ticketfy
    restart: always
    tty: true
    volumes:
      - db:/data/postgres
    ports:
      - "5432:5432"
    env_file:
      - .env

  migration:
    container_name: migrations
    build: .
    env_file:
      - .env
    command:
      [
        "./wait-for-it/wait-for-it.sh",
        "postgres:5432",
        "--",
        "npm",
        "run",
        "migrate:docker"
      ]
    links:
      - postgres
    depends_on:
      - postgres

volumes:
  db:
